- operation: Add
  participant_description:
    name: Ward45Bot
    group: w45bot
    responsiveness: Responsive
    profile:
      footprint:
        type: Circle
        index: "\x00"
      vicinity:
        type: Circle
        index: "\x01"
      shape_context:
        - 0.5
        - 0.5